### PR TITLE
Adding free non-tracking Contrast tool

### PR DESCRIPTION
**Pull request by erikcostlow**
#  #

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] _All_ future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Review by nikmartin — COMMENTED** [review]
Is this just blog spam? Why does CISA owe you a link?

**Comment by erikcostlow** [comment]
There's an entire tool here that connects to JVMs and patches the issue. You can take the blog out if you'd like.

**Comment by genericcontributor** [comment]
this is not the intent here at all, and patching is an exercise left up to the owner. This also assumes direct access to the jar, which we wouldnt (necessarily) have from a remote scanning solution. Closing.

**Comment by nikmartin** [comment]
> There's an entire tool here that connects to JVMs and patches the issue. You can take the blog out if you'd like.

Which is not the intent of this tool at all. This is the most bizarre pull request I think I've ever read. You know this is a remote scanning tool, correct? Why would you have access to replace a jar file from a remote scan on port 443?

**Pull request closed without merging**
